In [2]:
import pandas as pd

In [41]:
#Create a dataframe from list of list
data =[['Rahul',None],['Mohan','50'],['neha','90'],['Satendra','77'],['pooja','76']]
ds = pd.DataFrame(data,columns = ['Name','Nmber'])
print(ds)
print(ds.shape)

       Name Nmber
0     Rahul  None
1     Mohan    50
2      neha    90
3  Satendra    77
4     pooja    76
(5, 2)

In [20]:
#craete dataFrame from Dictionary
data = {"a":[55,67,78],"b":[89,87,78]}
ds = pd.DataFrame(data)
print(ds)

    a   b
0  55  89
1  67  87
2  78  78

In [19]:
#Create DataFrame from numpy
import numpy as np
arr = [[1,2],[3,4],[4,5]]
ds = pd.DataFrame(arr,columns = ['a','b'])
print(ds)

   a  b
0  1  2
1  3  4
2  4  5

In [31]:
#read axcel file
pd.read_excel('student_marks.xlsx')

    Name  Subject  Marks       Date
0   Anuj     Math     85 2026-03-14
1  Rahul  Science     90 2026-03-14
2   Amit  English     78 2026-03-14

In [35]:
#read the data from csv file
pd.read_csv('data.csv')

    Name  Subject  Marks        Date
0   Anuj     Math     85  2026-03-14
1  Rahul  Science     90  2026-03-14
2   Amit  English     78  2026-03-14

In [40]:
#read data from json file
dataframe = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')
dataframe

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [41]:
#EDA -: Exploratory Data Analysis
# df.head()         # First 5 rows
# df.tail()         # Last 5 rows
# df.info()         # Column info: types, non-nulls
# df.describe()     # Stats for numeric columns
# df.columns        # List of column names
# df.shape          # (rows, columns)

dataframe.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [43]:

dataframe.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [44]:

dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [45]:
dataframe.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [50]:
dataframe.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [51]:
dataframe.shape

(150, 5)

In [59]:
#Database
# import pandas as pd
# import mysql.connector

# conn = mysql.connector.connect(
#     host="localhost",
#     user="root",
#     password="root",
#     database="book_review"
# )

# query = "SELECT * FROM books"

# df = pd.read_sql(query, conn)

# print(df)

from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("mysql+pymysql://root:root@localhost/book_review")

df = pd.read_sql("SELECT * FROM books", engine)

print(df)

ModuleNotFoundError: No module named 'pymysql'