In [1]:
#Import pandas
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [7]:
#Selecting Columns
print(df["Actor"])

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [9]:
#Selecting Multiple Columns
print(df[["Actor", "Film"]])

                 Actor                      Film
0       Shah Rukh Khan                   Pathaan
1          Salman Khan           Tiger Zinda Hai
2           Aamir Khan                    Dangal
3        Ranbir Kapoor                Brahmastra
4        Ranveer Singh                 Padmaavat
5   Ayushmann Khurrana                 Andhadhun
6        Rajkummar Rao                     Stree
7       Hrithik Roshan                       War
8         Akshay Kumar                Good Newwz
9        Kartik Aaryan         Bhool Bhulaiyaa 2
10        Varun Dhawan     Badrinath Ki Dulhania
11       Vicky Kaushal  Uri: The Surgical Strike

In [12]:
#Selecting Rows by Index

df.loc[0] #By the row

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [13]:
df.iloc[0]   #By the position

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [23]:
#Select Specific Rows and Columns
df.loc[0, "Film"]        # Value at row 0, column 'Name'
df.iloc[0, 1]            # Value at row 0, column at index 1

'Pathaan'

In [24]:
df.loc[0:2,["Actor","Film"]] # Rows 0 to 2, selected columnsd

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai
2      Aamir Khan           Dangal

In [25]:
df.iloc[0:2, 0:2]              # Rows and cols by index position

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

In [26]:
#Fast Access: .at and .iat
df.at[0, "Actor"]       # Fast label-based access
df.iat[0, 1]           # Fast position-based access

'Pathaan'

In [30]:
#Filtering with Conditions
df[df["IMDb"] > 6]['Actor']

0         Shah Rukh Khan
2             Aamir Khan
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [33]:
#Multiple Conditions (AND / OR)
df[(df["IMDb"] > 5) & (df["Actor"] == "Shah Rukh Khan")]
# df[(df["Name"] == "Bob") | (df["Age"] < 30)]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

***Querying with .query()***
1. Column names become variables
2. String values must be in quotes
3. Use backticks for column names with spaces or special characters
4. You can use @ to reference Python variables
5. Logical operators
6. Chained comparisons
7. Avoid using reserved keywords as column names
8. Case-sensitive
9. .query() returns a copy, not a view

In [34]:
df.query("IMDb > 5 and Actor == 'Akshay Kumar'")

          Actor        Film  Year   Genre  BoxOffice(INR Crore)  IMDb
8  Akshay Kumar  Good Newwz  2019  Comedy                   318   7.0

In [35]:
#Dynamic column names:
col = "Actor"
df.query(f"{col} == 'Akshay Kumar'")

          Actor        Film  Year   Genre  BoxOffice(INR Crore)  IMDb
8  Akshay Kumar  Good Newwz  2019  Comedy                   318   7.0

In [36]:
#1. Column names become variables
df.query("IMDb > 5 and Actor == 'Akshay Kumar'")

          Actor        Film  Year   Genre  BoxOffice(INR Crore)  IMDb
8  Akshay Kumar  Good Newwz  2019  Comedy                   318   7.0

In [37]:
#2. String values must be in quotes
df.query("Actor == 'Akshay Kumar'")

          Actor        Film  Year   Genre  BoxOffice(INR Crore)  IMDb
8  Akshay Kumar  Good Newwz  2019  Comedy                   318   7.0

In [38]:
#3Use backticks for column names with spaces or special characters
#df.query("`first name` == 'Alice'")

In [39]:
#4. You can use @ to reference Python variables
IMDb = 6
df.query("IMDb > @IMDb")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [40]:
#5. Logical operators
#df.query("age > 30 and city == 'Delhi'")  # ✅

In [41]:
#6. Chained comparisons
df.query("5 < IMDb <= 9")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [42]:
#7. Avoid using reserved keywords as column names
#If you have a column named class, lambda, etc., you’ll need to use backticks:
#df.query("`class` == 'Physics'")

In [43]:
# 8. Case-sensitive
# Column names and string values are case-sensitive:

In [ ]:
# 9. .query() returns a copy, not a view
# The result is a new DataFrame. Changes won't affect the original unless reassigned:
# filtered = df.query("age < 50")