***Data Cleaning & Preprocessing***

In [5]:
#import pandas
import pandas as pd

In [6]:
data =pd.read_csv("data_cleaning_sample.csv")
data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

***Check for Missing Data***

In [7]:
#show null 
data.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [8]:
#sum of null count
data.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

***Drop Missing Data***

In [9]:
data.dropna() # Drop rows with *any* missing values

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [10]:
data.dropna(axis=1) # Drop columns with missing values

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

***Fill Missing Data***

In [11]:
data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [12]:
data.fillna(0) 
# Replace NaN with 0

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [13]:
#replace with mean
data['Age'].fillna(data['Age'].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [14]:
data.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [15]:
data.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

***Detecting & Removing Duplicates***

In [16]:
data.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [17]:
data.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [18]:
data.duplicated(subset=["Name", "Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

***String Operations with .str***

In [19]:
data["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [20]:
data["City"].str.contains("delhi", case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

***Type Conversions with .astype()***

In [24]:
df = pd.DataFrame(data)

In [25]:
df["Age"] = data["Age"].astype(int)
df["Date"] = pd.to_datetime(df["Date"])
df["Category"] = df["Category"].astype("category")

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

***Applying Functions***

In [ ]:
#.apply() → Apply any function to rows or columns
data['Age Group'] = data['Age'].apply(lambda x: "Adult" if x >= 18 else "Minor")
data

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

In [26]:
#.map() → Element-wise mapping for Series
gender_map = {"M": "Male", "F": "Female"}
data["Gender"] = data["Gender"].map(gender_map)
data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York    NaN  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi    NaN    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles    NaN    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi    NaN    charlie@example  20-07-2021
4    David  22.0       Mumbai    NaN  david@example.com  12-11-2019
5      NaN  28.0        Delhi    NaN     eve@domain.com         NaN
6    Alice  25.0     New York    NaN  alice@example.com  01-05-2021
7    Alice  25.0     New York    NaN  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi    NaN    charlie@example  20-07-2021

In [ ]:
#.replace() → Replace specific values
data["City"].replace({"Del": "Delhi", "Mum": "Mumbai"})

0       New York
1          Delhi
2    Los Angeles
3          Delhi
4         Mumbai
5          Delhi
6       New York
7       New York
8          Delhi
Name: City, dtype: object