***Sorting & Ranking***

In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("data_cleaning_sample.csv")
data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [5]:
data.sort_values("Age")

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [7]:
data.sort_values("Age", ascending=False) # Descending

      Name   Age         City Gender              Email   Join Date
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [13]:
data.sort_values(["Age", "Gender"]) # Sort by multiple columns

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

***Reset Index***

In [15]:
data.reset_index(drop=True, inplace=True)
# Reset the index and drop the old index

In [14]:
data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

***Sort by Index***

In [16]:
data.sort_index()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [22]:
data["Rank"] = data["Age"].rank()
data

      Name   Age         City Gender              Email   Join Date  Rank
0    Alice  25.0     New York      F  alice@example.com  01-05-2021   3.0
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   6.0
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN
4    David  22.0       Mumbai      M  david@example.com  12-11-2019   1.0
5      NaN  28.0        Delhi      F     eve@domain.com         NaN   5.0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021   3.0
7    Alice  25.0     New York      F  alice@example.com  01-05-2021   3.0
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN

In [26]:
data["Rank"] = data["Age"].rank(method="dense") # 1, 2, 2, 3
data

      Name   Age         City Gender              Email   Join Date  Rank
0    Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   4.0
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN
4    David  22.0       Mumbai      M  david@example.com  12-11-2019   1.0
5      NaN  28.0        Delhi      F     eve@domain.com         NaN   3.0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
7    Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN

***Renaming Columns & Index***

In [ ]:
# df.rename(columns={"oldName": "newName"}, inplace=True)
# df.rename(index={0: "row1", 1: "row2"}, inplace=True)
#df.columns = ["Name", "Age", "City"]  #Rename all column

***Changing Column Order***

In [27]:
#df = df[["City", "Name", "Age"]]
# Reorder as desired

In [ ]:
#cols = ["Name"] + [col for col in df.columns if col != "Name"]
#df = df[cols]