In [2]:
import pandas as pd

```
Level 1 (Basic Pandas)
Read the CSV file.
Display the first 5 rows.
Display the last 5 rows.
Find the number of rows and columns.
Show column names.
Check data types.
Display dataset information.
Generate summary statistics.
```

In [3]:
#1. Read the Csv file
emp = pd.read_csv('employees.csv')
print(emp)

    EmployeeID    Name    Age  Department    Salary       City  Experience  \
0          101    Anuj   30.0          IT   50000.0      Delhi           5
1          102    Ravi   25.0          HR   35000.0     Jaipur           2
2          103    Aman    NaN          IT   45000.0     Indore           3
3          104   Pooja   29.0     Finance   60000.0      Delhi           6
4          105    Ravi   25.0          HR   35000.0     Jaipur           2
5          106    Neha   31.0          IT       NaN     Mumbai           7
6          107   Karan   45.0  Management  120000.0      Delhi          20
7          108   Priya   28.0     Finance   58000.0      Delhi           5
8          109   Vikas  150.0          IT   48000.0       Pune           4
9          110     NaN   26.0       Sales   42000.0  Ahmedabad           3
10         111   Rohit   27.0       Sales   41000.0  Ahmedabad           3
11         112  Anjali   29.0          HR   37000.0     Jaipur           5
12         113  Deepak   32.0          IT   52000.0      Delhi           8
13         114  Simran   24.0     Finance   39000.0     Mumbai           1
14         115    Amit   -5.0       Sales   43000.0       Pune           2
15         115    Amit   -5.0       Sales   43000.0       Pune           2

   JoiningDate
0   2020-05-12
1   2022-06-15
2   2021-03-20
3   2019-08-18
4   2022-06-15
5   2018-04-10
6   2005-02-01
7   2020-11-11
8   2021-09-01
9   2022-10-05
10  2022-10-05
11  2020-01-01
12  2017-06-25
13  2023-01-15
14  2023-03-10
15  2023-03-10

2. Display first 5 rows.

In [202]:
print(emp.head())

   EmployeeID   Name   Age Department   Salary    City  Experience JoiningDate
0         101   Anuj  30.0         IT  50000.0   Delhi           5  2020-05-12
1         102   Ravi  25.0         HR  35000.0  Jaipur           2  2022-06-15
2         103   Aman   NaN         IT  45000.0  Indore           3  2021-03-20
3         104  Pooja  29.0    Finance  60000.0   Delhi           6  2019-08-18
4         105   Ravi  25.0         HR  35000.0  Jaipur           2  2022-06-15

3. Display Last 5 record.

In [203]:
print(emp.tail())

    EmployeeID    Name   Age Department   Salary    City  Experience  \
11         112  Anjali  29.0         HR  37000.0  Jaipur           5
12         113  Deepak  32.0         IT  52000.0   Delhi           8
13         114  Simran  24.0    Finance  39000.0  Mumbai           1
14         115    Amit  -5.0      Sales  43000.0    Pune           2
15         115    Amit  -5.0      Sales  43000.0    Pune           2

   JoiningDate
11  2020-01-01
12  2017-06-25
13  2023-01-15
14  2023-03-10
15  2023-03-10

3. Find Numbers of rows and colomns.

In [204]:
print(emp.shape)

(16, 8)

4. Show colomn names.

In [205]:
print(emp.columns)

Index(['EmployeeID', 'Name', 'Age', 'Department', 'Salary', 'City',
       'Experience', 'JoiningDate'],
      dtype='object')

5. Check DataType.

In [206]:

print(emp['EmployeeID'].dtype)

int64

Display dataset information.

In [207]:
print(emp.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   16 non-null     int64
 1   Name         15 non-null     object
 2   Age          15 non-null     float64
 3   Department   16 non-null     object
 4   Salary       15 non-null     float64
 5   City         16 non-null     object
 6   Experience   16 non-null     int64
 7   JoiningDate  16 non-null     object
dtypes: float64(2), int64(2), object(4)
memory usage: 1.1+ KB
None


Generate summary statistics.

In [208]:
print(emp.describe())

       EmployeeID         Age         Salary  Experience
count   16.000000   15.000000      15.000000      16.000
mean   108.437500   32.733333   49866.666667       4.875
std      4.661455   34.933542   20839.065878       4.500
min    101.000000   -5.000000   35000.000000       1.000
25%    104.750000   25.000000   40000.000000       2.000
50%    108.500000   28.000000   43000.000000       3.500
75%    112.250000   30.500000   51000.000000       5.250
max    115.000000  150.000000  120000.000000      20.000

```
Level 2 (Data Exploration)
Find all missing values.
Count missing values in each column.
Count the total number of employees.
List all unique departments.
Count employees in each department.
Count employees in each city.
Find the average salary.
Find the maximum salary.
Find the minimum salary.
Find the median salary.
Find the standard deviation of salaries.
```

Find all missing values

In [5]:

pd.isnull(emp)

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,True,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,True,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False

Count missing values in each column.

In [210]:
print(pd.isnull(emp).sum())

EmployeeID     0
Name           1
Age            1
Department     0
Salary         1
City           0
Experience     0
JoiningDate    0
dtype: int64

Count the total number of employees.

In [211]:
print(emp['EmployeeID'].count())

16

In [212]:
len(emp)

16

In [213]:
emp.shape[0]

16

List all unique departments.

In [214]:
print(emp['Department'].unique() )

['IT' 'HR' 'Finance' 'Management' 'Sales']

In [215]:
print(emp['Department'].nunique())

5

Count employees in each department.

In [216]:
print(emp['Department'].value_counts())

Department
IT            5
Sales         4
HR            3
Finance       3
Management    1
Name: count, dtype: int64

Count employees in each city.

In [217]:
print(emp['City'].value_counts())

City
Delhi        5
Jaipur       3
Pune         3
Mumbai       2
Ahmedabad    2
Indore       1
Name: count, dtype: int64

Find the average salary.last 3place

In [218]:
print(f"Mean of Salary: {emp['Salary'].mean():.3f}")

Mean of Salary: 49866.667


Find the maximum salary.

In [6]:
print(f"Max salary is : {emp['Salary'].max():.2f}")

Max salary is : 120000.00

Find the minimum salary.

In [7]:
print(f"Min salary is : {emp['Salary'].min():.2f}")

Min salary is : 35000.00

Find the median salary.

In [221]:
print(f"Median of Salary: {emp['Salary'].median():.3f}")

Median of Salary: 43000.000

Find the standard deviation of salaries.

In [222]:
print(f"standard deviation of Salary: {emp['Salary'].std():.3f}")

standard deviation of Salary: 20839.066

```
Level 3 (Filtering)
Employees with salary greater than ₹50,000.
Employees from the IT department.
Employees from Delhi.
Employees whose experience is greater than 5 years.
Employees aged between 25 and 30.
Employees whose names start with "A".
Employees in IT earning more than ₹45,000.
Employees who joined after 2021.
```

Employees with salary greater than ₹50,000.

In [223]:
emp[emp['Salary'] > 50000]

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18
6,107,Karan,45.0,Management,120000.0,Delhi,20,2005-02-01
7,108,Priya,28.0,Finance,58000.0,Delhi,5,2020-11-11
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25

Employees from the IT department.

In [224]:
dep = 'IT'
emp[emp['Department'] == dep]

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12
2,103,Aman,NaN,IT,45000.0,Indore,3,2021-03-20
5,106,Neha,31.0,IT,NaN,Mumbai,7,2018-04-10
8,109,Vikas,150.0,IT,48000.0,Pune,4,2021-09-01
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25

Employees from Delhi.

In [225]:
City = 'Delhi'
emp[emp['City'] == City]

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18
6,107,Karan,45.0,Management,120000.0,Delhi,20,2005-02-01
7,108,Priya,28.0,Finance,58000.0,Delhi,5,2020-11-11
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25

Employees whose experience is greater than 5 years.

In [226]:
emp[emp['Experience'] > 5]

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18
5,106,Neha,31.0,IT,NaN,Mumbai,7,2018-04-10
6,107,Karan,45.0,Management,120000.0,Delhi,20,2005-02-01
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25

Employees aged between 25 and 30.

In [13]:
emp[(emp['Age'] > 25) & (emp['Age'] < 30)]

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18
7,108,Priya,28.0,Finance,58000.0,Delhi,5,2020-11-11
9,110,NaN,26.0,Sales,42000.0,Ahmedabad,3,2022-10-05
10,111,Rohit,27.0,Sales,41000.0,Ahmedabad,3,2022-10-05
11,112,Anjali,29.0,HR,37000.0,Jaipur,5,2020-01-01

In [9]:
emp[(emp['Age'] >= 25) | (emp['Age'] <= 30)]

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12
1,102,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18
4,105,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15
5,106,Neha,31.0,IT,NaN,Mumbai,7,2018-04-10
6,107,Karan,45.0,Management,120000.0,Delhi,20,2005-02-01
7,108,Priya,28.0,Finance,58000.0,Delhi,5,2020-11-11
8,109,Vikas,150.0,IT,48000.0,Pune,4,2021-09-01
9,110,NaN,26.0,Sales,42000.0,Ahmedabad,3,2022-10-05
10,111,Rohit,27.0,Sales,41000.0,Ahmedabad,3,2022-10-05
11,112,Anjali,29.0,HR,37000.0,Jaipur,5,2020-01-01
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25
13,114,Simran,24.0,Finance,39000.0,Mumbai,1,2023-01-15
14,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10
15,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10

Employees whose names start with "A".

In [229]:
emp[emp['Name'].str.lower().str.startswith('a',na=False)]

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12
2,103,Aman,NaN,IT,45000.0,Indore,3,2021-03-20
11,112,Anjali,29.0,HR,37000.0,Jaipur,5,2020-01-01
14,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10
15,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10

Employees in IT earning more than ₹45,000.

In [230]:
emp[(emp['Department'] == 'IT') & (emp['Salary'] > 50000)]

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25

Employees who joined after 2021.

In [231]:
emp[emp['JoiningDate'] > '2021-12-31']

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
1,102,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15
4,105,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15
9,110,NaN,26.0,Sales,42000.0,Ahmedabad,3,2022-10-05
10,111,Rohit,27.0,Sales,41000.0,Ahmedabad,3,2022-10-05
13,114,Simran,24.0,Finance,39000.0,Mumbai,1,2023-01-15
14,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10
15,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10

Level 4 (Sorting)
Sort employees by salary (ascending).
Sort employees by age (descending).
Sort by department and salary.

Sort employees by salary (ascending).

In [232]:
emp.sort_values(by='Salary', ascending=True)

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
1,102,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15
4,105,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15
11,112,Anjali,29.0,HR,37000.0,Jaipur,5,2020-01-01
13,114,Simran,24.0,Finance,39000.0,Mumbai,1,2023-01-15
10,111,Rohit,27.0,Sales,41000.0,Ahmedabad,3,2022-10-05
9,110,NaN,26.0,Sales,42000.0,Ahmedabad,3,2022-10-05
14,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10
15,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10
2,103,Aman,NaN,IT,45000.0,Indore,3,2021-03-20
8,109,Vikas,150.0,IT,48000.0,Pune,4,2021-09-01
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25
7,108,Priya,28.0,Finance,58000.0,Delhi,5,2020-11-11
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18
6,107,Karan,45.0,Management,120000.0,Delhi,20,2005-02-01
5,106,Neha,31.0,IT,NaN,Mumbai,7,2018-04-10

Sort employees by age (descending).

In [233]:
emp.sort_values(by='Salary', ascending=False)

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
6,107,Karan,45.0,Management,120000.0,Delhi,20,2005-02-01
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18
7,108,Priya,28.0,Finance,58000.0,Delhi,5,2020-11-11
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12
8,109,Vikas,150.0,IT,48000.0,Pune,4,2021-09-01
2,103,Aman,NaN,IT,45000.0,Indore,3,2021-03-20
14,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10
15,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10
9,110,NaN,26.0,Sales,42000.0,Ahmedabad,3,2022-10-05
10,111,Rohit,27.0,Sales,41000.0,Ahmedabad,3,2022-10-05
13,114,Simran,24.0,Finance,39000.0,Mumbai,1,2023-01-15
11,112,Anjali,29.0,HR,37000.0,Jaipur,5,2020-01-01
1,102,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15
4,105,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15
5,106,Neha,31.0,IT,NaN,Mumbai,7,2018-04-10

Sort by department and salary.

In [234]:
emp.sort_values(by=['Department', 'Salary'], ascending=False)

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
14,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10
15,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10
9,110,NaN,26.0,Sales,42000.0,Ahmedabad,3,2022-10-05
10,111,Rohit,27.0,Sales,41000.0,Ahmedabad,3,2022-10-05
6,107,Karan,45.0,Management,120000.0,Delhi,20,2005-02-01
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12
8,109,Vikas,150.0,IT,48000.0,Pune,4,2021-09-01
2,103,Aman,NaN,IT,45000.0,Indore,3,2021-03-20
5,106,Neha,31.0,IT,NaN,Mumbai,7,2018-04-10
11,112,Anjali,29.0,HR,37000.0,Jaipur,5,2020-01-01
1,102,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15
4,105,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18
7,108,Priya,28.0,Finance,58000.0,Delhi,5,2020-11-11
13,114,Simran,24.0,Finance,39000.0,Mumbai,1,2023-01-15

```
Level 5 (Data Cleaning)
    Find duplicate records.
    Remove duplicates.
    Find employees with missing names.
    Fill missing salaries with the average salary.
    Fill missing ages with the median age.
    Remove employees with invalid ages (Age < 18 or Age > 60).
    Remove extra spaces from text columns (if any).
    Convert all city names to uppercase.
    Convert department names to lowercase.
```

Find duplicate records.

In [235]:
print(emp[emp.duplicated()])

    EmployeeID  Name  Age Department   Salary  City  Experience JoiningDate
15         115  Amit -5.0      Sales  43000.0  Pune           2  2023-03-10

In [242]:
emp[emp.duplicated(subset=['EmployeeID','Name'], keep='first')]

    EmployeeID  Name  Age Department   Salary  City  Experience JoiningDate
15         115  Amit -5.0      Sales  43000.0  Pune           2  2023-03-10

Remove duplicates.

In [247]:
emp.drop_duplicates(subset=['EmployeeID','Name'], keep='first', inplace=True)

emp.tail()

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
10,111,Rohit,27.0,Sales,41000.0,Ahmedabad,3,2022-10-05
11,112,Anjali,29.0,HR,37000.0,Jaipur,5,2020-01-01
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25
13,114,Simran,24.0,Finance,39000.0,Mumbai,1,2023-01-15
14,115,Amit,-5.0,Sales,43000.0,Pune,2,2023-03-10

Find employees with missing names.

In [249]:
emp[emp['Name'].isnull()]

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
9,110,NaN,26.0,Sales,42000.0,Ahmedabad,3,2022-10-05

Fill missing salaries with the average salary.

In [250]:
emp[emp['Salary'].isnull()]

   EmployeeID  Name   Age Department  Salary    City  Experience JoiningDate
5         106  Neha  31.0         IT     NaN  Mumbai           7  2018-04-10

In [257]:
emp.fillna(emp['Salary'].mean(), inplace=True)
emp['Salary']

0      50000.000000
1      35000.000000
2      45000.000000
3      60000.000000
4      35000.000000
5      50357.142857
6     120000.000000
7      58000.000000
8      48000.000000
9      42000.000000
10     41000.000000
11     37000.000000
12     52000.000000
13     39000.000000
14     43000.000000
Name: Salary, dtype: float64

Fill missing ages with the median age.

In [ ]:
emp.isnull().sum()

# emp.fillna(emp['Age'].median(), inplace=True)

EmployeeID     0
Name           0
Age            0
Department     0
Salary         0
City           0
Experience     0
JoiningDate    0
dtype: int64

Remove employees with invalid ages (Age < 18 or Age > 60).

In [269]:
emp[(emp['Age'] < 18) | (emp['Age'] > 60)]

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
2,103,Aman,50357.142857,IT,45000.0,Indore,3,2021-03-20
8,109,Vikas,150.000000,IT,48000.0,Pune,4,2021-09-01
14,115,Amit,-5.000000,Sales,43000.0,Pune,2,2023-03-10

In [271]:
emp.drop(emp[(emp['Age'] < 18) | (emp['Age'] > 60)].index, inplace=True)

In [272]:
emp[(emp['Age'] < 18) | (emp['Age'] > 60)]

Empty DataFrame
Columns: [EmployeeID, Name, Age, Department, Salary, City, Experience, JoiningDate]
Index: []

Remove extra spaces from text columns (if any).

In [273]:
for col in emp.select_dtypes(include=['object']).columns:
    emp[col] = emp[col].str.strip().str.replace(r'\s+', ' ', regex=True)

Convert all city names to uppercase.

In [275]:
emp['City'] =  emp['City'].str.upper()

emp.head()

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate
0,101,Anuj,30.0,IT,50000.000000,DELHI,5,2020-05-12
1,102,Ravi,25.0,HR,35000.000000,JAIPUR,2,2022-06-15
3,104,Pooja,29.0,Finance,60000.000000,DELHI,6,2019-08-18
4,105,Ravi,25.0,HR,35000.000000,JAIPUR,2,2022-06-15
5,106,Neha,31.0,IT,50357.142857,MUMBAI,7,2018-04-10

Convert department names to lowercase.

In [277]:
emp['Department'] = emp['Department'].str.lower()

emp['Department']

0             it
1             hr
3        finance
4             hr
5             it
6     management
7        finance
9          sales
10         sales
11            hr
12            it
13       finance
Name: Department, dtype: object

```
Level 6 (Adding Columns)
Create a Bonus column (10% of Salary).
Create an AnnualSalary column.
Create an ExperienceCategory column:
Junior (<3 years)
Mid (3–6 years)
Senior (>6 years)
Create an AgeGroup column:
Young (18–30)
Adult (31–45)
Senior (46+)
```

Create a Bonus column (10% of Salary).

In [15]:
emp['Bonus'] = (emp['Salary'] * 0.10).round(2)
emp.head()

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate,Bonus
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12,5000.0
1,102,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15,3500.0
2,103,Aman,NaN,IT,45000.0,Indore,3,2021-03-20,4500.0
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18,6000.0
4,105,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15,3500.0

Create an AnnualSalary column.

In [16]:
# Create an AnnualSalary column.
emp['AnnualSalary'] = round(emp['Salary'] * 12,2)
emp.head()

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate,Bonus,AnnualSalary
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12,5000.0,600000.0
1,102,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15,3500.0,420000.0
2,103,Aman,NaN,IT,45000.0,Indore,3,2021-03-20,4500.0,540000.0
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18,6000.0,720000.0
4,105,Ravi,25.0,HR,35000.0,Jaipur,2,2022-06-15,3500.0,420000.0

```
Create an ExperienceCategory column:
Junior (<3 years)
Mid (3–6 years)
Senior (>6 years)
```

In [285]:
# 1. Initialize the column with a default value
emp['ExperienceCategory'] = 'Unknown'

# 2. Assign 'Junior' to rows where Experience is less than 3
emp.loc[emp['Experience'] < 3, 'ExperienceCategory'] = 'Junior'

# 3. Assign 'Mid' to rows where Experience is between 3 and 6 (inclusive)
emp.loc[(emp['Experience'] >= 3) & (emp['Experience'] <= 6), 'ExperienceCategory'] = 'Mid'

# 4. Assign 'Senior' to rows where Experience is greater than 6
emp.loc[emp['Experience'] > 6, 'ExperienceCategory'] = 'Senior'

# View the results
print(emp[['Name', 'Experience', 'ExperienceCategory']].head())

    Name  Experience ExperienceCategory
0   Anuj           5                Mid
1   Ravi           2             Junior
3  Pooja           6                Mid
4   Ravi           2             Junior
5   Neha           7             Senior

```
Level 8 (Advanced)
Find the top 5 highest-paid employees.
Find the lowest-paid employee in each department.
Find employees whose salary is above the overall average.
Find employees who have the same name.
Calculate salary percentage contribution of each employee.
Find the oldest employee.
Find the newest employee (latest joining date).
Find employees with more than 10 years of experience.
Find employees earning less than the department average.
Save the cleaned dataset as cleaned_employees.csv.
Export department-wise salary statistics to a new CSV.
Bonus Challenges (Interview Level)
Detect salary outliers using the IQR method.
Replace outlier salaries with the median salary.
Rank employees by salary.
Find the second highest salary.
Display the top 3 employees from each department based on salary.
Find the percentage of missing values in each column.
Merge this dataset with another department dataset.
Create a pivot table showing average salary by city and department.
Create a crosstab of Department vs City.
Visualize salary distribution using a histogram.
```

In [ ]:
#Find the top 5 highest-paid employees.

emp.sort_values(by=['Salary'], ascending=False).head(5)

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate,Bonus,AnnualSalary
6,107,Karan,45.0,Management,120000.0,Delhi,20,2005-02-01,12000.0,1440000.0
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18,6000.0,720000.0
7,108,Priya,28.0,Finance,58000.0,Delhi,5,2020-11-11,5800.0,696000.0
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25,5200.0,624000.0
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12,5000.0,600000.0

In [21]:
emp.nlargest(5, 'Salary')

,EmployeeID,Name,Age,Department,Salary,City,Experience,JoiningDate,Bonus,AnnualSalary
6,107,Karan,45.0,Management,120000.0,Delhi,20,2005-02-01,12000.0,1440000.0
3,104,Pooja,29.0,Finance,60000.0,Delhi,6,2019-08-18,6000.0,720000.0
7,108,Priya,28.0,Finance,58000.0,Delhi,5,2020-11-11,5800.0,696000.0
12,113,Deepak,32.0,IT,52000.0,Delhi,8,2017-06-25,5200.0,624000.0
0,101,Anuj,30.0,IT,50000.0,Delhi,5,2020-05-12,5000.0,600000.0

In [22]:
# Find the lowest-paid employee in each department.
emp.groupby('Department')['Salary'].min()

Department
Finance        39000.0
HR             35000.0
IT             45000.0
Management    120000.0
Sales          41000.0
Name: Salary, dtype: float64