Import all the required libraries

In [1]:
import numpy as np
import pandas as pd

Generate the fake data

nominal data

In [2]:
np.random.seed(0)
num_samples = 1000
# create a nominal column
colors = ['red', 'blue', 'green', 'yellow', 'black']
nominal_data = np.random.choice(colors, num_samples)

# create dataframe
df = pd.DataFrame(nominal_data, columns=['Color'])
df

      Color
0     black
1       red
2    yellow
3    yellow
4    yellow
..      ...
995   black
996  yellow
997    blue
998    blue
999  yellow

[1000 rows x 1 columns]

ordinal data

In [3]:
satisfaction_levels = ['low', 'medium', 'high']
ordinal_data = np.random.choice(satisfaction_levels, num_samples, p = [0.3, 0.4, 0.3])
df['satisfaction_levels'] = ordinal_data
df

      Color satisfaction_levels
0     black              medium
1       red                 low
2    yellow              medium
3    yellow                 low
4    yellow              medium
..      ...                 ...
995   black                 low
996  yellow                high
997    blue                 low
998    blue              medium
999  yellow                 low

[1000 rows x 2 columns]

interval data

In [4]:
np.random.seed(0)

# interval data => temperature in the range from 0 to 100
interval_data = np.random.randint(0, 100, num_samples)

df['temperature'] = interval_data
df

      Color satisfaction_levels  temperature
0     black              medium           44
1       red                 low           47
2    yellow              medium           64
3    yellow                 low           67
4    yellow              medium           67
..      ...                 ...          ...
995   black                 low           26
996  yellow                high           48
997    blue                 low           71
998    blue              medium           54
999  yellow                 low           96

[1000 rows x 3 columns]

ratio data

In [5]:
# generate the fake data
ratio_data = np.random.rand(num_samples) * 1000 # income in dollars

df['income'] = ratio_data
df

      Color satisfaction_levels  temperature      income
0     black              medium           44  891.800965
1       red                 low           47  780.931133
2    yellow              medium           64  211.533898
3    yellow                 low           67  764.994448
4    yellow              medium           67  189.062660
..      ...                 ...          ...         ...
995   black                 low           26  953.563226
996  yellow                high           48   84.288156
997    blue                 low           71  951.102251
998    blue              medium           54   34.989338
999  yellow                 low           96  538.944405

[1000 rows x 4 columns]

discrete data -> num_of_children

In [6]:
discrete_data = np.random.randint(1, 10, num_samples)

df['number_of_children'] = discrete_data
df

      Color satisfaction_levels  temperature      income  number_of_children
0     black              medium           44  891.800965                   5
1       red                 low           47  780.931133                   3
2    yellow              medium           64  211.533898                   1
3    yellow                 low           67  764.994448                   2
4    yellow              medium           67  189.062660                   6
..      ...                 ...          ...         ...                 ...
995   black                 low           26  953.563226                   2
996  yellow                high           48   84.288156                   2
997    blue                 low           71  951.102251                   8
998    blue              medium           54   34.989338                   3
999  yellow                 low           96  538.944405                   8

[1000 rows x 5 columns]

continuous data -> weight

In [7]:
continuous_data = np.random.rand(num_samples) * 10 # weights in kg
df['weights'] = pd.DataFrame(continuous_data, columns=['weights'])
df

,Color,satisfaction_levels,temperature,income,number_of_children,weights
0,black,medium,44,891.800965,5,3.129535
1,red,low,47,780.931133,3,6.147365
2,yellow,medium,64,211.533898,1,3.703743
3,yellow,low,67,764.994448,2,4.852117
4,yellow,medium,67,189.062660,6,0.819175
...,...,...,...,...,...,...
995,black,low,26,953.563226,2,1.689129
996,yellow,high,48,84.288156,2,3.267756
997,blue,low,71,951.102251,8,1.931996
998,blue,medium,54,34.989338,3,0.331442
999,yellow,low,96,538.944405,8,5.839594

In [8]:
df.to_excel('types_of_data.xlsx')

Measures Of Dispersion

In [9]:
data = pd.read_csv('/content/process_engineering_data.csv')
data.head()

                             process_id  temperature    pressure  flow_rate
0  26bac532-89b5-493d-94cb-3d5dda8f425c    52.483571  127.987109  26.624109
1  08e6adcb-f775-4d17-b129-e24ba29ee93d    49.308678  118.492674  29.277407
2  74d101ae-d735-4a90-b512-c836c7fa7ec5    53.238443  101.192607  26.037900
3  25ac6436-4f7c-4002-80ed-c31906434f38    57.615149   87.061264  28.460192
4  2fdcad4c-cf71-4606-a457-cab5e04fe203    48.829233  113.964466  20.531927

Range Of temperature

In [10]:
temp_range = data['temperature'].max() - data['temperature'].min()
print(temp_range)

35.46999415361897

Interquartile Range => Q3 - Q1

In [11]:
Q1 = data['temperature'].quantile(0.25)
Q3 = data['temperature'].quantile(0.75)
temp_iqr = Q3 - Q1
print(temp_iqr)

6.477670904676408

Variance of the pressure column

In [12]:
var_pressure = data['pressure'].var()
print(var_pressure)

397.96609386005645

Standard Deviation of the pressure column

In [13]:
std_pressure = data['pressure'].std()
print(std_pressure)

19.94908754454841

Measures of Central Tendency

In [14]:
data['pressure'].mean()

np.float64(101.41672474498311)

In [15]:
data['pressure'].median()

101.26154264658092

In [16]:
data['pressure'].mode()

0       41.192227
1       41.572990
2       42.074892
3       42.554756
4       43.029148
          ...
995    151.791273
996    152.033662
997    152.886867
998    162.754971
999    163.862151
Name: pressure, Length: 1000, dtype: float64

Measure of skewness is done by skew() function.

In [18]:
flow_rate_skewness = data['flow_rate'].skew()

Data Distribution => Right Skewed

In [19]:
print(flow_rate_skewness)

1.331814813830591