Import all the required libraries

In [1]:
import numpy as np
import pandas as pd

Generate the fake data

Qualitative Data/nominal data

In [2]:
np.random.seed(0)
num_samples = 1000
# create a nominal column
colors = ['red', 'blue', 'green', 'yellow', 'black']
nominal_data = np.random.choice(colors, num_samples)

# create dataframe
df = pd.DataFrame(nominal_data, columns=['Color'])
df

      Color
0     black
1       red
2    yellow
3    yellow
4    yellow
..      ...
995   black
996  yellow
997    blue
998    blue
999  yellow

[1000 rows x 1 columns]

ordinal data

In [3]:
satisfaction_levels = ['low', 'medium', 'high']
ordinal_data = np.random.choice(satisfaction_levels, num_samples, p = [0.3, 0.4, 0.3])
df['satisfaction_levels'] = ordinal_data
df

      Color satisfaction_levels
0     black              medium
1       red                 low
2    yellow              medium
3    yellow                 low
4    yellow              medium
..      ...                 ...
995   black                 low
996  yellow                high
997    blue                 low
998    blue              medium
999  yellow                 low

[1000 rows x 2 columns]

Quantitative Data/Discrete Data

In [9]:
items = np.arange(1000,2000)
df['items'] = items
df

      Color satisfaction_levels  items
0     black              medium   1000
1       red                 low   1001
2    yellow              medium   1002
3    yellow                 low   1003
4    yellow              medium   1004
..      ...                 ...    ...
995   black                 low   1995
996  yellow                high   1996
997    blue                 low   1997
998    blue              medium   1998
999  yellow                 low   1999

[1000 rows x 3 columns]

Quantitative Data/Continuous Data

In [17]:
cost = np.random.uniform(10000,200000,num_samples)
df['cost'] = cost
df['cost'] = df['cost'].round(2)
df

      Color satisfaction_levels  items       cost
0     black              medium   1000   93896.76
1       red                 low   1001   59729.48
2    yellow              medium   1002   65861.67
3    yellow                 low   1003   45799.62
4    yellow              medium   1004  183445.92
..      ...                 ...    ...        ...
995   black                 low   1995   17885.50
996  yellow                high   1996   12373.53
997    blue                 low   1997   67784.25
998    blue              medium   1998   55665.14
999  yellow                 low   1999   83757.31

[1000 rows x 4 columns]

write a file

In [20]:
df.to_csv('types_of_data.csv')

range of items

In [23]:
range = df['items'].max() - df['items'].min()
print(range)

999

Interquartile Range => Q3 - Q1

In [28]:
Q1 = df['items'].quantile(0.25)
Q3 = df['items'].quantile(0.75)
temp_iqr = Q3 - Q1
print(temp_iqr)

499.5

Variance of the cosr column

In [29]:
std_pressure = df['cost'].std()
print(std_pressure)

54306.052856082686

Measures of Central Tendency

In [30]:
df['cost'].mean()

np.float64(104521.90006)

In [31]:
df['cost'].median()

106836.745

In [32]:
df['cost'].mode()

0       10543.35
1       10558.71
2       10961.78
3       11224.75
4       11225.55
         ...
995    198501.98
996    198790.78
997    199317.08
998    199343.15
999    199548.67
Name: cost, Length: 1000, dtype: float64

Measure of skewness is done by skew() function.

In [34]:
flow_rate_skewness = df['cost'].skew()
flow_rate_skewness

np.float64(-0.02742485394098484)

Data Distribution => Right Skewed

In [35]:
print(flow_rate_skewness)

-0.02742485394098484