Local system: pip install pandas

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import load_breast_cancer

In [2]:
data = sns.load_dataset("tips")
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
type(data['sex'])

pandas.core.series.Series

In [5]:
type(data[['sex', 'day']])

pandas.core.frame.DataFrame

Customized Series

In [6]:
data = [10, 20, 30, 40, 50, 60]
series1 = pd.Series(data)
series1

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [7]:
data = [10, 20, 30, 40, 50, 60]
series2 = pd.Series(data, index=['a', 'b', 'c', 'd', 'e', 'f'])
series2

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [8]:
s1 = pd.Series([10, 20, 30], index = ['a', 'b', 'c'])
s2 = pd.Series([5, 15, 25], index = ['b', 'c', 'd'])

result = s1 + s2

print(result)

a     NaN
b    25.0
c    45.0
d     NaN
dtype: float64

In [9]:
a1 = np.array([10, 20, 30])
a2 = np.array([5, 15, 25])

print(a1 + a2)

[15 35 55]

Create a series from a NumPy array

In [10]:
a1

array([10, 20, 30])

In [11]:
a1_series = pd.Series(a1, index = ['a', 'b', 'c'])
a1_series

a    10
b    20
c    30
dtype: int64

In [12]:
print(a1_series.iloc[1])

20

In [13]:
print(a1_series.loc['b'])

20

Create a series from a dictionary

In [14]:
data = {'Alice':30, 'Bob':35, 'Charlie':28}

series = pd.Series(data)
print(series)

Alice      30
Bob        35
Charlie    28
dtype: int64

In [15]:
dataframe = pd.DataFrame([data])
dataframe

   Alice  Bob  Charlie
0     30   35       28

In [16]:
data

{'Alice': 30, 'Bob': 35, 'Charlie': 28}

In [17]:
data = pd.read_excel('/content/customers.xlsx')

# head() method used to access the top 5 records in a given dataframe
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

Access the columns: [email, gender, street_name, city, state]

Access the rows: [1, 2, 5, 9, 12]

In [18]:
data.loc[(1,2,5,9,12),["email","gender","street_name","city","state"]]

                     email  gender  street_name         city      state
1    cmolyneaux1@wiley.com    Male          NaN      El Paso      Texas
2   bwestrip2@symantec.com  Female     Arkansas  San Antonio      Texas
5         mcullip5@tiny.cc  Female      Packers    Baltimore   Maryland
9       spoulden9@xing.com  Female         Pond  New Orleans  Louisiana
12     mmacwhanc@patch.com    Male  Eagle Crest        Bronx   New York

iloc vs loc -> to access the values in a given dataframe

In [19]:
data.iloc[[1,2,5,9,12],[3,4,6,8,9]]

                     email  gender  street_name         city      state
1    cmolyneaux1@wiley.com    Male          NaN      El Paso      Texas
2   bwestrip2@symantec.com  Female     Arkansas  San Antonio      Texas
5         mcullip5@tiny.cc  Female      Packers    Baltimore   Maryland
9       spoulden9@xing.com  Female         Pond  New Orleans  Louisiana
12     mmacwhanc@patch.com    Male  Eagle Crest        Bronx   New York

iloc -> you can access any row/column using the index numbers only

In [20]:
first_name_column = data.iloc[:, 1]

In [21]:
first_name_column

0       Romain
1       Cosimo
2        Bambi
3       Roarke
4      Mikaela
        ...
995    Merrili
996    Winonah
997      Tobit
998     Issiah
999     Elmore
Name: first_name, Length: 1000, dtype: object

Access the column as 'street_name'

In [22]:
street_name_column = data.iloc[:, 6]

In [23]:
street_name_column

0      Trailsway
1            NaN
2       Arkansas
3           Debs
4            2nd
         ...
995     Thompson
996      Rowland
997        Basil
998      Kenwood
999      Farwell
Name: street_name, Length: 1000, dtype: object

Access the rows having index number [1, 2, 3] and the column name [firstName, lastName, Gender]

In [24]:
data.iloc[1:4, [1, 2, 4]]

  first_name   last_name  gender
1     Cosimo   Molyneaux    Male
2      Bambi     Westrip  Female
3     Roarke  Pankettman    Male

loc -> to access the elements using the label-based indexing

In [25]:
data.loc[1:4, ['first_name', 'last_name', 'gender']]

  first_name   last_name  gender
1     Cosimo   Molyneaux    Male
2      Bambi     Westrip  Female
3     Roarke  Pankettman    Male
4    Mikaela    Althorpe     NaN

Attributes

In [26]:
# index -> return an index object contains the row lables of the dataframe
data.index

RangeIndex(start=0, stop=1000, step=1)

In [27]:
# shape -> return the (number of rows, number of columns) in a given dataframe
data.shape

(1000, 11)

In [28]:
data.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'street_num',
       'street_name', 'street_suffix', 'city', 'state', 'postcode'],
      dtype='object')

In [29]:
data.dtypes

id                 int64
first_name        object
last_name         object
email             object
gender            object
street_num       float64
street_name       object
street_suffix     object
city              object
state             object
postcode         float64
dtype: object

In [30]:
data.values

array([[1, 'Romain', 'Southcott', ..., 'San Diego', 'California',
        92127.0],
       [2, 'Cosimo', 'Molyneaux', ..., 'El Paso', 'Texas', nan],
       [3, 'Bambi', 'Westrip', ..., 'San Antonio', 'Texas', 78220.0],
       ...,
       [998, 'Tobit', 'Birt', ..., 'Waterbury', 'Connecticut', 6721.0],
       [999, 'Issiah', 'Standbrooke', ..., 'Savannah', 'Georgia',
        31405.0],
       [1000, 'Elmore', 'Malpas', ..., 'Atlanta', 'Georgia', 30386.0]],
      dtype=object)

In [31]:
data.size

11000

In [32]:
data.empty

False

In [33]:
data.ndim

2

Functions in a dataframe

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   first_name     1000 non-null   object
 2   last_name      1000 non-null   object
 3   email          878 non-null    object
 4   gender         957 non-null    object
 5   street_num     738 non-null    float64
 6   street_name    963 non-null    object
 7   street_suffix  963 non-null    object
 8   city           921 non-null    object
 9   state          920 non-null    object
 10  postcode       843 non-null    float64
dtypes: float64(2), int64(1), object(8)
memory usage: 86.1+ KB

In [35]:
data.isnull().sum()

id                 0
first_name         0
last_name          0
email            122
gender            43
street_num       262
street_name       37
street_suffix     37
city              79
state             80
postcode         157
dtype: int64

In [36]:
data.head(20)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,NaN,530.0,Erie,Plaza,Kansas City,Missouri,64193.0
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,NaN
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0
11,12,Noni,Norrington,nnorringtonb@netvibes.com,Female,5.0,NaN,NaN,Baltimore,Maryland,21282.0
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0
13,14,Deny,Thraves,dthravesd@ibm.com,Female,71865.0,Valley Edge,Place,Washington,District of Columbia,20456.0
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,NaN,Claremont,Place,Los Angeles,California,90005.0
15,16,Jodie,De Cristoforo,jdecristoforof@mac.com,Male,50948.0,Rowland,Alley,Charleston,South Carolina,29424.0
16,17,Tobi,Dewicke,tdewickeg@hostgator.com,Female,6817.0,Orin,Junction,San Rafael,NaN,NaN
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,NaN,Northwestern,Way,Amarillo,Texas,79118.0
18,19,Fredek,Foley,ffoleyi@bbb.org,Male,8.0,Ridgeway,Park,Silver Spring,Maryland,20910.0
19,20,Rubina,Hustings,rhustingsj@wikimedia.org,Female,249.0,Esker,Hill,San Antonio,Texas,78210.0

In [37]:
data.tail()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [38]:
data.tail(20)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
980,981,Phylys,Taggerty,ptaggertyr8@epa.gov,Female,92462.0,Maple,Court,Nashville,Tennessee,37250.0
981,982,Judith,Otham,NaN,Female,96973.0,Saint Paul,Avenue,Arlington,Texas,76096.0
982,983,Allison,Coogan,acooganra@auda.org.au,Female,81.0,Thompson,Drive,Orange,California,92867.0
983,984,Adolph,Hammerton,ahammertonrb@quantcast.com,Male,NaN,Basil,Crossing,Orlando,Florida,32813.0
984,985,Tailor,Sealeaf,tsealeafrc@irs.gov,Male,NaN,Summer Ridge,Pass,Beaufort,South Carolina,29905.0
985,986,Lidia,Glendza,lglendzard@techcrunch.com,Female,90.0,Golf Course,Circle,Clearwater,Florida,NaN
986,987,Eric,Mountford,emountfordre@blogspot.com,Male,NaN,6th,Court,Las Vegas,Nevada,89125.0
987,988,Angelica,Ludlamme,aludlammerf@unc.edu,Female,5849.0,Steensland,Park,Saint Petersburg,Florida,NaN
988,989,Vivianne,Abbyss,vabbyssrg@squarespace.com,Female,53592.0,Larry,Road,Santa Cruz,California,95064.0
989,990,Mari,Carberry,mcarberryrh@eventbrite.com,Female,NaN,1st,Drive,Washington,District of Columbia,20546.0
990,991,Susana,Pere,spereri@scribd.com,Female,5018.0,Clemons,Way,Baton Rouge,NaN,70820.0
991,992,Silvie,Silverlock,ssilverlockrj,Female,NaN,Elka,Avenue,Utica,New York,13505.0
992,993,Johnath,Clancy,jclancyrk@smugmug.com,Female,7.0,Washington,Crossing,Juneau,Alaska,99812.0
993,994,Binnie,Dearth,bdearthrl@ed.gov,NaN,8993.0,Elgar,Trail,Minneapolis,Minnesota,55441.0
994,995,Brana,Dixon,bdixonrm@myspace.com,Female,97.0,Truax,Avenue,Maple Plain,Minnesota,55572.0
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [39]:
data

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

Summary of the descriptive statistics

In [40]:
data.describe()

                id    street_num      postcode
count  1000.000000    738.000000    843.000000
mean    500.500000  10536.439024  52669.548043
std     288.819436  23050.537603  28140.041026
min       1.000000      0.000000    214.000000
25%     250.750000     21.000000  29279.500000
50%     500.500000    445.500000  48232.000000
75%     750.250000   6918.500000  78337.500000
max    1000.000000  99918.000000  99812.000000

In [41]:
data.describe(include='all')

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
count,1000.000000,1000,1000,878,957,738.000000,963,963,921,920,843.000000
unique,NaN,932,993,878,2,NaN,427,21,296,48,NaN
top,NaN,Berty,Sedworth,istandbrookerq@yellowpages.com,Male,NaN,Weeping Birch,Place,Washington,Texas,NaN
freq,NaN,4,3,1,485,NaN,6,57,29,107,NaN
mean,500.500000,NaN,NaN,NaN,NaN,10536.439024,NaN,NaN,NaN,NaN,52669.548043
std,288.819436,NaN,NaN,NaN,NaN,23050.537603,NaN,NaN,NaN,NaN,28140.041026
min,1.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,214.000000
25%,250.750000,NaN,NaN,NaN,NaN,21.000000,NaN,NaN,NaN,NaN,29279.500000
50%,500.500000,NaN,NaN,NaN,NaN,445.500000,NaN,NaN,NaN,NaN,48232.000000
75%,750.250000,NaN,NaN,NaN,NaN,6918.500000,NaN,NaN,NaN,NaN,78337.500000
max,1000.000000,NaN,NaN,NaN,NaN,99918.000000,NaN,NaN,NaN,NaN,99812.000000

In [42]:
data.transpose()

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
id,1,2,3,4,5,6,7,8,9,10,...,991,992,993,994,995,996,997,998,999,1000
first_name,Romain,Cosimo,Bambi,Roarke,Mikaela,Magdalena,Marietta,Tine,Enrichetta,Sari,...,Susana,Silvie,Johnath,Binnie,Brana,Merrili,Winonah,Tobit,Issiah,Elmore
last_name,Southcott,Molyneaux,Westrip,Pankettman,Althorpe,Cullip,Heball,McSperrin,de Villier,Poulden,...,Pere,Silverlock,Clancy,Dearth,Dixon,Alman,Heckle,Birt,Standbrooke,Malpas
email,rsouthcott0@clickbank.net,cmolyneaux1@wiley.com,bwestrip2@symantec.com,rpankettman3@wiley.com,malthorpe4@51.la,mcullip5@tiny.cc,mheball6@blog.com,tmcsperrin7@statcounter.com,edevillier8@ox.ac.uk,spoulden9@xing.com,...,spereri@scribd.com,ssilverlockrj,jclancyrk@smugmug.com,bdearthrl@ed.gov,bdixonrm@myspace.com,malmanrn@cornell.edu,whecklero@fc2.com,NaN,istandbrookerq@yellowpages.com,NaN
gender,Male,Male,Female,Male,NaN,Female,Female,NaN,Female,Female,...,Female,Female,Female,NaN,Female,Female,Female,Male,Male,Male
street_num,1.0,NaN,4057.0,74.0,NaN,9190.0,12.0,530.0,745.0,2.0,...,5018.0,NaN,7.0,8993.0,97.0,0.0,701.0,2.0,NaN,205.0
street_name,Trailsway,NaN,Arkansas,Debs,2nd,Packers,Mallory,Erie,Annamark,Pond,...,Clemons,Elka,Washington,Elgar,Truax,Thompson,Rowland,Basil,Kenwood,Farwell
street_suffix,Road,NaN,Circle,Point,Drive,Drive,Center,Plaza,Street,Hill,...,Way,Avenue,Crossing,Trail,Avenue,Way,Hill,Road,Drive,Park
city,San Diego,El Paso,San Antonio,Memphis,NaN,Baltimore,Carol Stream,Kansas City,Fairbanks,New Orleans,...,Baton Rouge,Utica,Juneau,Minneapolis,Maple Plain,Reading,Indianapolis,Waterbury,Savannah,Atlanta
state,California,Texas,Texas,Tennessee,NaN,Maryland,Illinois,Missouri,Alaska,Louisiana,...,NaN,New York,Alaska,Minnesota,Minnesota,Pennsylvania,Indiana,Connecticut,Georgia,Georgia
postcode,92127.0,NaN,78220.0,38150.0,83732.0,21229.0,60351.0,64193.0,99709.0,NaN,...,70820.0,13505.0,99812.0,55441.0,55572.0,19610.0,46278.0,6721.0,31405.0,30386.0

In [43]:
df_cat = data.select_dtypes(include='object')
df_cat

,first_name,last_name,email,gender,street_name,street_suffix,city,state
0,Romain,Southcott,rsouthcott0@clickbank.net,Male,Trailsway,Road,San Diego,California
1,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,El Paso,Texas
2,Bambi,Westrip,bwestrip2@symantec.com,Female,Arkansas,Circle,San Antonio,Texas
3,Roarke,Pankettman,rpankettman3@wiley.com,Male,Debs,Point,Memphis,Tennessee
4,Mikaela,Althorpe,malthorpe4@51.la,NaN,2nd,Drive,NaN,NaN
...,...,...,...,...,...,...,...,...
995,Merrili,Alman,malmanrn@cornell.edu,Female,Thompson,Way,Reading,Pennsylvania
996,Winonah,Heckle,whecklero@fc2.com,Female,Rowland,Hill,Indianapolis,Indiana
997,Tobit,Birt,NaN,Male,Basil,Road,Waterbury,Connecticut
998,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,Kenwood,Drive,Savannah,Georgia
999,Elmore,Malpas,NaN,Male,Farwell,Park,Atlanta,Georgia

In [44]:
df_num = data.select_dtypes(include=['int64', 'float64'])
df_num

       id  street_num  postcode
0       1         1.0   92127.0
1       2         NaN       NaN
2       3      4057.0   78220.0
3       4        74.0   38150.0
4       5         NaN   83732.0
..    ...         ...       ...
995   996         0.0   19610.0
996   997       701.0   46278.0
997   998         2.0    6721.0
998   999         NaN   31405.0
999  1000       205.0   30386.0

[1000 rows x 3 columns]

In [45]:
df_num = data.select_dtypes(include='number')
df_num

       id  street_num  postcode
0       1         1.0   92127.0
1       2         NaN       NaN
2       3      4057.0   78220.0
3       4        74.0   38150.0
4       5         NaN   83732.0
..    ...         ...       ...
995   996         0.0   19610.0
996   997       701.0   46278.0
997   998         2.0    6721.0
998   999         NaN   31405.0
999  1000       205.0   30386.0

[1000 rows x 3 columns]

Operations on rows and columns in a dataframe

In [46]:
data

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

Add a new column in a dataframe

In [47]:
data['Country'] = 'USA'
data

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,USA
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,USA
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA

Observation: Pandas expects that the length of the membership_status list should be exactly equivalent to the number of rows or it could be a single value which is applicable to all the rows or it could be some logic which is applicable for all the rows. Otherwise, it will throw an error.

In [48]:
membership_status = ['Gold', 'Silver', 'Bronze']
data['Membership Status'] = membership_status
data

ValueError: Length of values (3) does not match length of index (1000)

Create a new column named 'full_name' which is composed of first_name and last_name and that too after last_name column

In [49]:
data.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'street_num',
       'street_name', 'street_suffix', 'city', 'state', 'postcode', 'Country'],
      dtype='object')

get_loc() functions is used to access the index of the last_name column

In [50]:
idx = data.columns.get_loc('last_name')
print(idx)

2

In [51]:
new_col_idx = data.columns.get_loc('last_name') + 1
data.insert(
    loc = new_col_idx,
    column = 'full_name',
    value = data['first_name'] + ' ' + data['last_name']
)

data

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA
3,4,Roarke,Pankettman,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA
4,5,Mikaela,Althorpe,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,USA
996,997,Winonah,Heckle,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,USA
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA

Add a new row

In [52]:
data.loc['1000'] = [1001,'Romain', 'Westrip', 'bwestrip52@symantec.com', 'Male', 90.0, None,None, None, 'Georgia', 83732.0, 'USA', 'Romain Westrip']
data.tail()

/tmp/ipython-input-2071127949.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data.loc['1000'] = [1001,'Romain', 'Westrip', 'bwestrip52@symantec.com', 'Male', 90.0, None,None, None, 'Georgia', 83732.0, 'USA', 'Romain Westrip']

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
996,997,Winonah,Heckle,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,USA
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA
1000,1001,Romain,Westrip,bwestrip52@symantec.com,Male,90.0,NaN,None,None,Georgia,83732.0,USA,Romain Westrip

Delete row/column in a given dataframe

In [54]:
data.tail()

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
996,997,Winonah,Heckle,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,USA
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA
1000,1001,Romain,Westrip,bwestrip52@symantec.com,Male,90.0,NaN,None,None,Georgia,83732.0,USA,Romain Westrip

Drop a row

In [55]:
data.drop(index='1000', inplace=True)
data.tail()

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
995,996,Merrili,Alman,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,USA
996,997,Winonah,Heckle,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,USA
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA

Drop a column

In [56]:
data.drop(columns=['first_name', 'last_name'], inplace=True)
data.head()

,id,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
0,1,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA
3,4,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA
4,5,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA

Rename row label of first row to 'FirstCustomer'

In [58]:
data.rename(index = {0: 'FirstCustomer'}, inplace=True)
data

,id,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
FirstCustomer,1,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA
3,4,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA
4,5,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,USA
996,997,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,USA
997,998,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA
998,999,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA
999,1000,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA

In [59]:
data.rename(index = {'FirstCustomer':0}, inplace = True)
data

,id,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
0,1,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA
3,4,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA
4,5,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,USA
996,997,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,USA
997,998,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA
998,999,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA
999,1000,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA

Rename column label of street_num to street_number

In [63]:
data.rename(columns = {
    'street_num': 'street_number'
}, inplace=True)

data

,id,full_name,email,gender,street_number,street_name,street_suffix,city,state,postcode,Country
0,1,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA
3,4,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA
4,5,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,USA
996,997,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,USA
997,998,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA
998,999,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA
999,1000,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA

Rename the 'street_name' column to 'street_address'

In [64]:
data.rename(columns = {'street_name': 'Street_address'}, inplace=True)
data

,id,full_name,email,gender,street_number,Street_address,street_suffix,city,state,postcode,Country
0,1,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA
3,4,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA
4,5,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,USA
996,997,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,USA
997,998,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA
998,999,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA
999,1000,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA

Find unique values

In [65]:
unique_genders = data['gender'].unique()
unique_genders

array(['Male', 'Female', nan], dtype=object)

In [66]:
count_unique_genders = data['gender'].nunique()
count_unique_genders

2

In [67]:
products = pd.read_excel('/content/products.xlsx')
purchases = pd.read_excel('/content/purchases.xlsx')

In [68]:
products.head()

   Unnamed: 0  id                           product    cost   company
0           0   1              Liners - Baking Cups   $6.36  Skipfire
1           1   2        Nori Sea Weed - Gold Label  $85.74   Dynazzy
2           2   3                Bar Bran Honey Nut  $65.40      Ntag
3           3   4        Soup - Campbells Beef Stew  $68.16  Photojam
4           4   5  Wine - Shiraz Wolf Blass Premium  $87.39      Eare

Drop the column name: 'Unnamed: 0' from the products dataframe

In [69]:
products.drop(columns=['Unnamed: 0'], inplace=True)
products

    id                             product    cost       company
0    1                Liners - Baking Cups   $6.36      Skipfire
1    2          Nori Sea Weed - Gold Label  $85.74       Dynazzy
2    3                  Bar Bran Honey Nut  $65.40          Ntag
3    4          Soup - Campbells Beef Stew  $68.16      Photojam
4    5    Wine - Shiraz Wolf Blass Premium  $87.39          Eare
5    6  Wine - White, Riesling, Semi - Dry  $99.22      Livepath
6    7                        Brandy - Bar  $13.83          Oloo
7    8                      Onions - White  $42.19          Oozz
8    9         Lettuce - Baby Salad Greens  $30.01        Meevee
9   10                Sambuca - Ramazzotti  $88.99      Livepath
10  11                Coffee - Decafenated  $21.47        Meezzy
11  12             Lamb Leg - Bone - In Nz  $42.56     Photofeed
12  13                Lettuce - Spring Mix  $19.90  Twitterworks
13  14              Cookies Oatmeal Raisin  $99.40       Dynabox
14  15              Cookies Oatmeal Raisin  $14.13          Vitz
15  16                   Sausage - Chorizo  $55.45           NaN
16  17                     Glaze - Apricot  $33.78    Browsezoom
17  18                           Squid Ink  $56.33         Aibox
18  19               Loaf Pan - 2 Lb, Foil  $22.83   Brainsphere
19  20        Bagel - Everything Presliced  $87.05        Trunyx
20  21          Bagel - Whole White Sesame  $90.48      Realcube
21  22                 Scotch - Queen Anne  $60.26           NaN
22  23                Puree - Blackcurrant  $16.27       Zoombox
23  24               Bread - Bagels, Plain  $31.26          Vitz
24  25               Snapple Raspberry Tea  $73.70       Innojam
25  26               Sour Puss - Tangerine  $84.20       Skinder
26  27                    Spaghetti Squash  $47.41           NaN
27  28         Wine - Niagara,vqa Reisling  $28.24           NaN
28  29                Iced Tea Concentrate  $59.23     Photolist
29  30                         Fuji Apples  $22.96       Cogibox
30  31      Wine - Carmenere Casillero Del  $55.77          Ntag
31  32                Container Clear 8 Oz  $92.33          Muxo
32  33                         Duck - Legs  $82.22       Voonder
33  34            Muffin Hinge Container 6  $99.54        Skyble
34  35          Pie Box - Cello Window 2.5  $95.68      Linkbuzz
35  36              Bread - English Muffin  $13.83         Quatz
36  37    Chocolate - Sugar Free Semi Choc  $61.99     Realpoint
37  38                   Pate - Peppercorn  $21.98         Mynte
38  39             Triple Sec - Mcguinness  $37.45         Oodoo
39  40                  Pepper - Cubanelle  $79.31       Cogibox
40  41                      Squash - Acorn  $65.35         Meemm
41  42                  Sauce - Demi Glace  $87.51      Wordware
42  43                   Pail For Lid 1537  $40.69      Edgeclub
43  44                        Foam Tray S2  $30.67  Jabbersphere
44  45                        Shark - Loin  $45.77  Thoughtstorm
45  46            Aromat Spice / Seasoning  $61.34           NaN
46  47                       Tobasco Sauce  $48.32    Browsezoom
47  48           Apple - Delicious, Golden  $36.67         Skiba
48  49                         Lamb - Rack  $62.60         Gevee
49  50              Silicone Paper 16.5x24  $63.98    Babbleopia
50  51               Ecolab - Power Fusion  $75.32      Fliptune
51  52          Soup - Knorr, Country Bean  $98.74        Eimbee
52  53            Chicken - Thigh, Bone In  $74.06   Topiclounge
53  54      Plate - Foam, Bread And Butter  $37.79     Flipstorm
54  55                     Beef - Bresaola   $8.55      Digitube
55  56                       Peach - Fresh  $20.53         Zazio
56  57                 Muffin Hinge - 211n  $68.63      Fanoodle
57  58                  Bar Bran Honey Nut  $73.05        Yakijo
58  59       Nut - Almond, Blanched, Whole  $74.28         Eazzy
59  60            Table Cloth 90x90 Colour  $41.22         Quinu

In [70]:
purchases.head()

,Unnamed: 0,id,purch_date,customer_num,product_num,amount,paid
0,0,1,2019-01-03 00:00:00,823,27,12,$568.92
1,1,2,2019-01-03 00:00:00,606,28,14,$395.36
2,2,3,2019-01-03 00:00:00,955,9,17,$510.17
3,3,4,2019-01-03 00:00:00,577,19,3,$68.49
4,4,5,2019-01-03 00:00:00,429,8,18,$759.42

In [71]:
purchases.drop(columns=['Unnamed: 0'], inplace=True)
purchases.head()

   id           purch_date  customer_num  product_num  amount     paid
0   1  2019-01-03 00:00:00           823           27      12  $568.92
1   2  2019-01-03 00:00:00           606           28      14  $395.36
2   3  2019-01-03 00:00:00           955            9      17  $510.17
3   4  2019-01-03 00:00:00           577           19       3   $68.49
4   5  2019-01-03 00:00:00           429            8      18  $759.42

In [75]:
purchases.dtypes

id               int64
purch_date      object
customer_num     int64
product_num      int64
amount           int64
paid            object
dtype: object

paid -> float

purch_date -> datetime

In [76]:
purchases['purch_date'] = pd.to_datetime(purchases['purch_date'])
purchases.dtypes

id                       int64
purch_date      datetime64[ns]
customer_num             int64
product_num              int64
amount                   int64
paid                    object
dtype: object

In [77]:
purchases['amount'] = purchases['amount'].astype(float)
purchases.dtypes

id                       int64
purch_date      datetime64[ns]
customer_num             int64
product_num              int64
amount                 float64
paid                    object
dtype: object

Convert the paid column to the float64 type

In [78]:
purchases['paid'] = purchases['paid'].astype(float)

ValueError: could not convert string to float: '$568.92'

Regular Expressions

In [79]:
purchases['paid'] = purchases['paid'].str.replace('[\$,]', '', regex=True)
purchases.head()

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-4103447545.py:1: SyntaxWarning: invalid escape sequence '\$'
  purchases['paid'] = purchases['paid'].str.replace('[\$,]', '', regex=True)

   id purch_date  customer_num  product_num  amount    paid
0   1 2019-01-03           823           27    12.0  568.92
1   2 2019-01-03           606           28    14.0  395.36
2   3 2019-01-03           955            9    17.0  510.17
3   4 2019-01-03           577           19     3.0   68.49
4   5 2019-01-03           429            8    18.0  759.42

In [80]:
purchases['paid'] = purchases['paid'].astype(float)
purchases.dtypes

id                       int64
purch_date      datetime64[ns]
customer_num             int64
product_num              int64
amount                 float64
paid                   float64
dtype: object

In [81]:
products.dtypes

id          int64
product    object
cost       object
company    object
dtype: object

In [82]:
products.head()

   id                           product    cost   company
0   1              Liners - Baking Cups   $6.36  Skipfire
1   2        Nori Sea Weed - Gold Label  $85.74   Dynazzy
2   3                Bar Bran Honey Nut  $65.40      Ntag
3   4        Soup - Campbells Beef Stew  $68.16  Photojam
4   5  Wine - Shiraz Wolf Blass Premium  $87.39      Eare

In [85]:
products['cost'] = products['cost'].str.replace('[\$,]','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-524076436.py:1: SyntaxWarning: invalid escape sequence '\$'
  products['cost'] = products['cost'].str.replace('[\$,]','',regex=True)

In [86]:
products['cost'] = products['cost'].astype(float)

In [87]:
products.dtypes

id           int64
product     object
cost       float64
company     object
sost        object
dtype: object

Statistical Operations

In [88]:
purchases.mean()

id                           3000.5
purch_date      2019-05-13 20:18:00
customer_num             500.889333
product_num               30.140667
amount                    10.576167
paid                     548.871353
dtype: object

In [89]:
purchases['paid'].mean()

np.float64(548.8713533333333)

In [90]:
purchases.median()

id                           3000.5
purch_date      2019-04-26 00:00:00
customer_num                  511.0
product_num                    30.0
amount                         11.0
paid                          422.7
dtype: object

Max values

In [91]:
max_values = purchases.max(numeric_only = True)
print(max_values)

id              6000.0
customer_num    1000.0
product_num       60.0
amount            20.0
paid            1990.8
dtype: float64

Sum Of Values

In [92]:
sum_values = purchases.sum(numeric_only = True)
print(sum_values)

id              18003000.00
customer_num     3005336.00
product_num       180844.00
amount             63457.00
paid             3293228.12
dtype: float64

Count the number of values

In [93]:
# count the non-null values in each column
column_count = products.count()
print(column_count)

id         60
product    60
cost       60
company    55
sost       60
dtype: int64

Frequency Analysis

In [94]:
products

    id                             product   cost       company    sost
0    1                Liners - Baking Cups   6.36      Skipfire   $6.36
1    2          Nori Sea Weed - Gold Label  85.74       Dynazzy  $85.74
2    3                  Bar Bran Honey Nut  65.40          Ntag  $65.40
3    4          Soup - Campbells Beef Stew  68.16      Photojam  $68.16
4    5    Wine - Shiraz Wolf Blass Premium  87.39          Eare  $87.39
5    6  Wine - White, Riesling, Semi - Dry  99.22      Livepath  $99.22
6    7                        Brandy - Bar  13.83          Oloo  $13.83
7    8                      Onions - White  42.19          Oozz  $42.19
8    9         Lettuce - Baby Salad Greens  30.01        Meevee  $30.01
9   10                Sambuca - Ramazzotti  88.99      Livepath  $88.99
10  11                Coffee - Decafenated  21.47        Meezzy  $21.47
11  12             Lamb Leg - Bone - In Nz  42.56     Photofeed  $42.56
12  13                Lettuce - Spring Mix  19.90  Twitterworks  $19.90
13  14              Cookies Oatmeal Raisin  99.40       Dynabox  $99.40
14  15              Cookies Oatmeal Raisin  14.13          Vitz  $14.13
15  16                   Sausage - Chorizo  55.45           NaN  $55.45
16  17                     Glaze - Apricot  33.78    Browsezoom  $33.78
17  18                           Squid Ink  56.33         Aibox  $56.33
18  19               Loaf Pan - 2 Lb, Foil  22.83   Brainsphere  $22.83
19  20        Bagel - Everything Presliced  87.05        Trunyx  $87.05
20  21          Bagel - Whole White Sesame  90.48      Realcube  $90.48
21  22                 Scotch - Queen Anne  60.26           NaN  $60.26
22  23                Puree - Blackcurrant  16.27       Zoombox  $16.27
23  24               Bread - Bagels, Plain  31.26          Vitz  $31.26
24  25               Snapple Raspberry Tea  73.70       Innojam  $73.70
25  26               Sour Puss - Tangerine  84.20       Skinder  $84.20
26  27                    Spaghetti Squash  47.41           NaN  $47.41
27  28         Wine - Niagara,vqa Reisling  28.24           NaN  $28.24
28  29                Iced Tea Concentrate  59.23     Photolist  $59.23
29  30                         Fuji Apples  22.96       Cogibox  $22.96
30  31      Wine - Carmenere Casillero Del  55.77          Ntag  $55.77
31  32                Container Clear 8 Oz  92.33          Muxo  $92.33
32  33                         Duck - Legs  82.22       Voonder  $82.22
33  34            Muffin Hinge Container 6  99.54        Skyble  $99.54
34  35          Pie Box - Cello Window 2.5  95.68      Linkbuzz  $95.68
35  36              Bread - English Muffin  13.83         Quatz  $13.83
36  37    Chocolate - Sugar Free Semi Choc  61.99     Realpoint  $61.99
37  38                   Pate - Peppercorn  21.98         Mynte  $21.98
38  39             Triple Sec - Mcguinness  37.45         Oodoo  $37.45
39  40                  Pepper - Cubanelle  79.31       Cogibox  $79.31
40  41                      Squash - Acorn  65.35         Meemm  $65.35
41  42                  Sauce - Demi Glace  87.51      Wordware  $87.51
42  43                   Pail For Lid 1537  40.69      Edgeclub  $40.69
43  44                        Foam Tray S2  30.67  Jabbersphere  $30.67
44  45                        Shark - Loin  45.77  Thoughtstorm  $45.77
45  46            Aromat Spice / Seasoning  61.34           NaN  $61.34
46  47                       Tobasco Sauce  48.32    Browsezoom  $48.32
47  48           Apple - Delicious, Golden  36.67         Skiba  $36.67
48  49                         Lamb - Rack  62.60         Gevee  $62.60
49  50              Silicone Paper 16.5x24  63.98    Babbleopia  $63.98
50  51               Ecolab - Power Fusion  75.32      Fliptune  $75.32
51  52          Soup - Knorr, Country Bean  98.74        Eimbee  $98.74
52  53            Chicken - Thigh, Bone In  74.06   Topiclounge  $74.06
53  54      Plate - Foam, Bread And Butter  37.79     Flipstorm  $37.79
54  55                     Beef - Bresaola   8.55      Digitube   $8.55
55  56                       Peach - Fresh  20.53         Zazio  $20.53
56  57                 Muffin Hinge - 211n  68.63      Fanoodle  $68.63
57  58                  Bar Bran Honey Nut  73.05        Yakijo  $73.05
58  59       Nut - Almond, Blanched, Whole  74.28         Eazzy  $74.28
59  60            Table Cloth 90x90 Colour  41.22         Quinu  $41.22

In [95]:
products['product'].value_counts()

product
Bar Bran Honey Nut                    2
Cookies Oatmeal Raisin                2
Nori Sea Weed - Gold Label            1
Soup - Campbells Beef Stew            1
Wine - Shiraz Wolf Blass Premium      1
Wine - White, Riesling, Semi - Dry    1
Brandy - Bar                          1
Onions - White                        1
Lettuce - Baby Salad Greens           1
Liners - Baking Cups                  1
Sambuca - Ramazzotti                  1
Coffee - Decafenated                  1
Lamb Leg - Bone - In Nz               1
Lettuce - Spring Mix                  1
Sausage - Chorizo                     1
Glaze - Apricot                       1
Squid Ink                             1
Loaf Pan - 2 Lb, Foil                 1
Bagel - Everything Presliced          1
Bagel - Whole White Sesame            1
Scotch - Queen Anne                   1
Puree - Blackcurrant                  1
Bread - Bagels, Plain                 1
Snapple Raspberry Tea                 1
Sour Puss - Tangerine                 1
Spaghetti Squash                      1
Wine - Niagara,vqa Reisling           1
Iced Tea Concentrate                  1
Fuji Apples                           1
Wine - Carmenere Casillero Del        1
Container Clear 8 Oz                  1
Duck - Legs                           1
Muffin Hinge Container 6              1
Pie Box - Cello Window 2.5            1
Bread - English Muffin                1
Chocolate - Sugar Free Semi Choc      1
Pate - Peppercorn                     1
Triple Sec - Mcguinness               1
Pepper - Cubanelle                    1
Squash - Acorn                        1
Sauce - Demi Glace                    1
Pail For Lid 1537                     1
Foam Tray S2                          1
Shark - Loin                          1
Aromat Spice / Seasoning              1
Tobasco Sauce                         1
Apple - Delicious, Golden             1
Lamb - Rack                           1
Silicone Paper 16.5x24                1
Ecolab - Power Fusion                 1
Soup - Knorr, Country Bean            1
Chicken - Thigh, Bone In              1
Plate - Foam, Bread And Butter        1
Beef - Bresaola                       1
Peach - Fresh                         1
Muffin Hinge - 211n                   1
Nut - Almond, Blanched, Whole         1
Table Cloth 90x90 Colour              1
Name: count, dtype: int64

In [96]:
data['gender'].value_counts()

gender
Male      485
Female    472
Name: count, dtype: int64

In [97]:
data['gender'].mode()

0    Male
Name: gender, dtype: object

Aggregate Functions

In [98]:
products['cost'].aggregate(['max', 'min'])

max    99.54
min     6.36
Name: cost, dtype: float64

Sorting the values

In [99]:
sorted_purchase = purchases.sort_values(by='amount')
sorted_purchase

        id purch_date  customer_num  product_num  amount     paid
5033  5034 2019-05-17           680           23     1.0    16.27
86      87 2019-01-04           651           25     1.0    73.70
5061  5062 2019-05-18           540           52     1.0    98.74
3363  3364 2019-03-29           457           10     1.0    88.99
1825  1826 2019-10-04           948           19     1.0    22.83
...    ...        ...           ...          ...     ...      ...
5037  5038 2019-05-17           508           42    20.0  1750.20
10      11 2019-01-03           727           47    20.0   966.40
11      12 2019-01-03           589           30    20.0   459.20
5985  5986 2019-06-20           238           33    20.0  1644.40
92      93 2019-01-04           312            9    20.0   600.20

[6000 rows x 6 columns]

In [101]:
sorted_purchase = purchases.sort_values(by='amount', ascending=False)
sorted_purchase

        id purch_date  customer_num  product_num  amount     paid
58      59 2019-01-04           577           42    20.0  1750.20
3351  3352 2019-03-29           809           23    20.0   325.40
3366  3367 2019-03-29           930           15    20.0   282.60
3388  3389 2019-03-29           155            1    20.0   127.20
3290  3291 2019-03-28           743           44    20.0   423.20
...    ...        ...           ...          ...     ...      ...
17      18 2019-01-03            40           60     1.0    41.22
59      60 2019-01-04           913           11     1.0    12.24
73      74 2019-01-04            92           41     1.0    65.35
95      96 2019-01-04           902           10     1.0    88.99
86      87 2019-01-04           651           25     1.0    73.70

[6000 rows x 6 columns]

idxmax => is used to return the index of the first occurence of the maximum value.

In [103]:
products

    id                             product   cost       company    sost
0    1                Liners - Baking Cups   6.36      Skipfire   $6.36
1    2          Nori Sea Weed - Gold Label  85.74       Dynazzy  $85.74
2    3                  Bar Bran Honey Nut  65.40          Ntag  $65.40
3    4          Soup - Campbells Beef Stew  68.16      Photojam  $68.16
4    5    Wine - Shiraz Wolf Blass Premium  87.39          Eare  $87.39
5    6  Wine - White, Riesling, Semi - Dry  99.22      Livepath  $99.22
6    7                        Brandy - Bar  13.83          Oloo  $13.83
7    8                      Onions - White  42.19          Oozz  $42.19
8    9         Lettuce - Baby Salad Greens  30.01        Meevee  $30.01
9   10                Sambuca - Ramazzotti  88.99      Livepath  $88.99
10  11                Coffee - Decafenated  21.47        Meezzy  $21.47
11  12             Lamb Leg - Bone - In Nz  42.56     Photofeed  $42.56
12  13                Lettuce - Spring Mix  19.90  Twitterworks  $19.90
13  14              Cookies Oatmeal Raisin  99.40       Dynabox  $99.40
14  15              Cookies Oatmeal Raisin  14.13          Vitz  $14.13
15  16                   Sausage - Chorizo  55.45           NaN  $55.45
16  17                     Glaze - Apricot  33.78    Browsezoom  $33.78
17  18                           Squid Ink  56.33         Aibox  $56.33
18  19               Loaf Pan - 2 Lb, Foil  22.83   Brainsphere  $22.83
19  20        Bagel - Everything Presliced  87.05        Trunyx  $87.05
20  21          Bagel - Whole White Sesame  90.48      Realcube  $90.48
21  22                 Scotch - Queen Anne  60.26           NaN  $60.26
22  23                Puree - Blackcurrant  16.27       Zoombox  $16.27
23  24               Bread - Bagels, Plain  31.26          Vitz  $31.26
24  25               Snapple Raspberry Tea  73.70       Innojam  $73.70
25  26               Sour Puss - Tangerine  84.20       Skinder  $84.20
26  27                    Spaghetti Squash  47.41           NaN  $47.41
27  28         Wine - Niagara,vqa Reisling  28.24           NaN  $28.24
28  29                Iced Tea Concentrate  59.23     Photolist  $59.23
29  30                         Fuji Apples  22.96       Cogibox  $22.96
30  31      Wine - Carmenere Casillero Del  55.77          Ntag  $55.77
31  32                Container Clear 8 Oz  92.33          Muxo  $92.33
32  33                         Duck - Legs  82.22       Voonder  $82.22
33  34            Muffin Hinge Container 6  99.54        Skyble  $99.54
34  35          Pie Box - Cello Window 2.5  95.68      Linkbuzz  $95.68
35  36              Bread - English Muffin  13.83         Quatz  $13.83
36  37    Chocolate - Sugar Free Semi Choc  61.99     Realpoint  $61.99
37  38                   Pate - Peppercorn  21.98         Mynte  $21.98
38  39             Triple Sec - Mcguinness  37.45         Oodoo  $37.45
39  40                  Pepper - Cubanelle  79.31       Cogibox  $79.31
40  41                      Squash - Acorn  65.35         Meemm  $65.35
41  42                  Sauce - Demi Glace  87.51      Wordware  $87.51
42  43                   Pail For Lid 1537  40.69      Edgeclub  $40.69
43  44                        Foam Tray S2  30.67  Jabbersphere  $30.67
44  45                        Shark - Loin  45.77  Thoughtstorm  $45.77
45  46            Aromat Spice / Seasoning  61.34           NaN  $61.34
46  47                       Tobasco Sauce  48.32    Browsezoom  $48.32
47  48           Apple - Delicious, Golden  36.67         Skiba  $36.67
48  49                         Lamb - Rack  62.60         Gevee  $62.60
49  50              Silicone Paper 16.5x24  63.98    Babbleopia  $63.98
50  51               Ecolab - Power Fusion  75.32      Fliptune  $75.32
51  52          Soup - Knorr, Country Bean  98.74        Eimbee  $98.74
52  53            Chicken - Thigh, Bone In  74.06   Topiclounge  $74.06
53  54      Plate - Foam, Bread And Butter  37.79     Flipstorm  $37.79
54  55                     Beef - Bresaola   8.55      Digitube   $8.55
55  56                       Peach - Fresh  20.53         Zazio  $20.53
56  57                 Muffin Hinge - 211n  68.63      Fanoodle  $68.63
57  58                  Bar Bran Honey Nut  73.05        Yakijo  $73.05
58  59       Nut - Almond, Blanched, Whole  74.28         Eazzy  $74.28
59  60            Table Cloth 90x90 Colour  41.22         Quinu  $41.22

In [104]:
idx_max_purchases = purchases.idxmax()
idx_max_purchases

id              5999
purch_date      2234
customer_num     352
product_num       17
amount            10
paid             211
dtype: int64

Return the average/mean value per company

In [107]:
group_by_company = products.groupby('company')
average_cost = group_by_company['cost'].mean()
print(average_cost)

company
Aibox           56.330
Babbleopia      63.980
Brainsphere     22.830
Browsezoom      41.050
Cogibox         51.135
Digitube         8.550
Dynabox         99.400
Dynazzy         85.740
Eare            87.390
Eazzy           74.280
Edgeclub        40.690
Eimbee          98.740
Fanoodle        68.630
Flipstorm       37.790
Fliptune        75.320
Gevee           62.600
Innojam         73.700
Jabbersphere    30.670
Linkbuzz        95.680
Livepath        94.105
Meemm           65.350
Meevee          30.010
Meezzy          21.470
Muxo            92.330
Mynte           21.980
Ntag            60.585
Oloo            13.830
Oodoo           37.450
Oozz            42.190
Photofeed       42.560
Photojam        68.160
Photolist       59.230
Quatz           13.830
Quinu           41.220
Realcube        90.480
Realpoint       61.990
Skiba           36.670
Skinder         84.200
Skipfire         6.360
Skyble          99.540
Thoughtstorm    45.770
Topiclounge     74.060
Trunyx          87.050
Twitterworks    19.900
Vitz            22.695
Voonder         82.220
Wordware        87.510
Yakijo          73.050
Zazio           20.530
Zoombox         16.270
Name: cost, dtype: float64

Concatenation -> combine dataframes along a particular axis (either rows or columns).

In [108]:
combined_df = pd.concat([data, purchases, products], axis=0)
print(combined_df)

    id          full_name                      email  gender  street_number  \
0    1   Romain Southcott  rsouthcott0@clickbank.net    Male            1.0
1    2   Cosimo Molyneaux      cmolyneaux1@wiley.com    Male            NaN
2    3      Bambi Westrip     bwestrip2@symantec.com  Female         4057.0
3    4  Roarke Pankettman     rpankettman3@wiley.com    Male           74.0
4    5   Mikaela Althorpe           malthorpe4@51.la     NaN            NaN
..  ..                ...                        ...     ...            ...
55  56                NaN                        NaN     NaN            NaN
56  57                NaN                        NaN     NaN            NaN
57  58                NaN                        NaN     NaN            NaN
58  59                NaN                        NaN     NaN            NaN
59  60                NaN                        NaN     NaN            NaN

   Street_address street_suffix         city       state postcode Country  \
0       Trailsway          Road    San Diego  California  92127.0     USA
1             NaN           NaN      El Paso       Texas      NaN     USA
2        Arkansas        Circle  San Antonio       Texas  78220.0     USA
3            Debs         Point      Memphis   Tennessee  38150.0     USA
4             2nd         Drive          NaN         NaN  83732.0     USA
..            ...           ...          ...         ...      ...     ...
55            NaN           NaN          NaN         NaN      NaN     NaN
56            NaN           NaN          NaN         NaN      NaN     NaN
57            NaN           NaN          NaN         NaN      NaN     NaN
58            NaN           NaN          NaN         NaN      NaN     NaN
59            NaN           NaN          NaN         NaN      NaN     NaN

   purch_date  customer_num  product_num  amount  paid  \
0         NaT           NaN          NaN     NaN   NaN
1         NaT           NaN          NaN     NaN   NaN
2         NaT           NaN          NaN     NaN   NaN
3         NaT           NaN          NaN     NaN   NaN
4         NaT           NaN          NaN     NaN   NaN
..        ...           ...          ...     ...   ...
55        NaT           NaN          NaN     NaN   NaN
56        NaT           NaN          NaN     NaN   NaN
57        NaT           NaN          NaN     NaN   NaN
58        NaT           NaN          NaN     NaN   NaN
59        NaT           NaN          NaN     NaN   NaN

                          product   cost   company    sost
0                             NaN    NaN       NaN     NaN
1                             NaN    NaN       NaN     NaN
2                             NaN    NaN       NaN     NaN
3                             NaN    NaN       NaN     NaN
4                             NaN    NaN       NaN     NaN
..                            ...    ...       ...     ...
55                  Peach - Fresh  20.53     Zazio  $20.53
56            Muffin Hinge - 211n  68.63  Fanoodle  $68.63
57             Bar Bran Honey Nut  73.05    Yakijo  $73.05
58  Nut - Almond, Blanched, Whole  74.28     Eazzy  $74.28
59       Table Cloth 90x90 Colour  41.22     Quinu  $41.22

[7060 rows x 20 columns]

In [109]:
combined_df_column_wise = pd.concat([data, purchases, products], axis=1)
print(combined_df_column_wise)

       id          full_name                      email  gender  \
0     1.0   Romain Southcott  rsouthcott0@clickbank.net    Male
1     2.0   Cosimo Molyneaux      cmolyneaux1@wiley.com    Male
2     3.0      Bambi Westrip     bwestrip2@symantec.com  Female
3     4.0  Roarke Pankettman     rpankettman3@wiley.com    Male
4     5.0   Mikaela Althorpe           malthorpe4@51.la     NaN
...   ...                ...                        ...     ...
5995  NaN                NaN                        NaN     NaN
5996  NaN                NaN                        NaN     NaN
5997  NaN                NaN                        NaN     NaN
5998  NaN                NaN                        NaN     NaN
5999  NaN                NaN                        NaN     NaN

      street_number Street_address street_suffix         city       state  \
0               1.0      Trailsway          Road    San Diego  California
1               NaN            NaN           NaN      El Paso       Texas
2            4057.0       Arkansas        Circle  San Antonio       Texas
3              74.0           Debs         Point      Memphis   Tennessee
4               NaN            2nd         Drive          NaN         NaN
...             ...            ...           ...          ...         ...
5995            NaN            NaN           NaN          NaN         NaN
5996            NaN            NaN           NaN          NaN         NaN
5997            NaN            NaN           NaN          NaN         NaN
5998            NaN            NaN           NaN          NaN         NaN
5999            NaN            NaN           NaN          NaN         NaN

     postcode  ... purch_date  customer_num product_num  amount    paid   id  \
0     92127.0  ... 2019-01-03           823          27    12.0  568.92  1.0
1         NaN  ... 2019-01-03           606          28    14.0  395.36  2.0
2     78220.0  ... 2019-01-03           955           9    17.0  510.17  3.0
3     38150.0  ... 2019-01-03           577          19     3.0   68.49  4.0
4     83732.0  ... 2019-01-03           429           8    18.0  759.42  5.0
...       ...  ...        ...           ...         ...     ...     ...  ...
5995      NaN  ... 2019-06-20           893          33     5.0  411.10  NaN
5996      NaN  ... 2019-06-20           566          23    11.0  178.97  NaN
5997      NaN  ... 2019-06-20           114          19     9.0  205.47  NaN
5998      NaN  ... 2019-06-20           404          11    20.0  429.40  NaN
5999      NaN  ... 2019-06-20            88          57     4.0  274.52  NaN

                               product   cost   company    sost
0                 Liners - Baking Cups   6.36  Skipfire   $6.36
1           Nori Sea Weed - Gold Label  85.74   Dynazzy  $85.74
2                   Bar Bran Honey Nut  65.40      Ntag  $65.40
3           Soup - Campbells Beef Stew  68.16  Photojam  $68.16
4     Wine - Shiraz Wolf Blass Premium  87.39      Eare  $87.39
...                                ...    ...       ...     ...
5995                               NaN    NaN       NaN     NaN
5996                               NaN    NaN       NaN     NaN
5997                               NaN    NaN       NaN     NaN
5998                               NaN    NaN       NaN     NaN
5999                               NaN    NaN       NaN     NaN

[6000 rows x 22 columns]

Merge Operation: SQL Joins

In [110]:
data.head()

,id,full_name,email,gender,street_number,Street_address,street_suffix,city,state,postcode,Country
0,1,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA
3,4,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA
4,5,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA

In [111]:
purchases.head()

   id purch_date  customer_num  product_num  amount    paid
0   1 2019-01-03           823           27    12.0  568.92
1   2 2019-01-03           606           28    14.0  395.36
2   3 2019-01-03           955            9    17.0  510.17
3   4 2019-01-03           577           19     3.0   68.49
4   5 2019-01-03           429            8    18.0  759.42

In [112]:
merged_df = pd.merge(data, purchases, on = 'id', how = 'inner')
merged_df

,id,full_name,email,gender,street_number,Street_address,street_suffix,city,state,postcode,Country,purch_date,customer_num,product_num,amount,paid
0,1,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA,2019-01-03,823,27,12.0,568.92
1,2,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA,2019-01-03,606,28,14.0,395.36
2,3,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA,2019-01-03,955,9,17.0,510.17
3,4,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA,2019-01-03,577,19,3.0,68.49
4,5,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA,2019-01-03,429,8,18.0,759.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,USA,2019-06-04,198,20,7.0,609.35
996,997,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,USA,2019-06-04,96,27,14.0,663.74
997,998,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA,2019-06-04,181,7,2.0,27.66
998,999,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA,2019-06-04,951,54,4.0,87.68
999,1000,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA,2019-06-04,435,20,18.0,1143.90

In [ ]:
'/content/products.xlsx'